paths:
  silver_sample: "datasets/annotation/silver_alaska_10_with_ids.jsonl"  # replace with your sample path
  train: "datasets/splits/train.jsonl"                                  # replace if your split paths differ
  val:   "datasets/splits/val.jsonl"
  test:  "datasets/splits/test.jsonl"
  eval_summary: "artifacts/eval/summary.csv"                            # replace if stored elsewhere
  policy_counts: "artifacts/policy/counts.csv"
  policy_decisions: "artifacts/policy/decisions.jsonl"

display:
  sample_chars: 140     # how many chars of text to show
  sample_decisions: 1   # how many policy decisions to print
  targets: ["ads_promo","spam_low_quality","irrelevant","rant_no_visit","relevancy_score","visit_likelihood"]
