data:
  test_path: "datasets/splits/test.jsonl"            # replace if your splits live elsewhere
  val_path: "datasets/splits/val.jsonl"              # replace if your splits live elsewhere

artifacts:
  preds_test: "artifacts/preds/test_preds.jsonl"      # replace with your prediction file path
  preds_val:  "artifacts/preds/val_preds.jsonl"       # replace with your prediction file path
  thresholds_json: "artifacts/models/thresholds.json" # written by training; replace if you stored thresholds elsewhere

schema:
  id_key: "review_id"

targets: ["ads_promo", "spam_low_quality", "irrelevant", "rant_no_visit"]

binarization:
  use_tuned_thresholds: true   # read per-target thresholds from thresholds_json

plots:
  roc_pr: true
  hist: true
  calibration: false
  dpi: 120

output:
  dir: "artifacts/eval"                                # choose your output directory
  plots_dir: "artifacts/plots"                         # choose where plots should go
  summary_json: "artifacts/eval/summary.json"
  summary_csv:  "artifacts/eval/summary.csv"
  report_md:    "artifacts/eval/report.md"

logging:
  ignore_warnings: true
  note_on_single_class: true
